# Generated by Django 4.2.7 on 2023-12-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctortable',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('available_days', models.CharField(max_length=100)),
                ('available_time', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
            ],
        ),
    ]
